spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/order_db
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}

  autoconfigure:
    exclude: org.springframework.cloud.gcp.autoconfigure.pubsub.health.PubSubHealthIndicatorAutoConfiguration

  cloud:
    gcp:
      pubsub:
        enabled: false

client:
  book:
    rootUrl: http://book-service:8080
    connectionTimeout: 3000ms
    socketTimeout: 3000ms
  user:
    rootUrl: http://user-service:8080
    connectionTimeout: 3000ms
    socketTimeout: 3000ms
