spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: postgres
    password: postgres123

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      show-sql: true
      ddl-auto: update

client:
  book:
    rootUrl: http://localhost:8080
    connectionTimeout: 3000ms
    socketTimeout: 3000ms
  user:
    rootUrl: http://localhost:8080
    connectionTimeout: 3000ms
    socketTimeout: 3000ms
